version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
